- name: demo on shell module
  hosts: all
  tasks:
    - name: execute shell command
      ansible.builtin.shell: uptime
      register: OUT_UPTIME

    - name: Printing OUT_UPTIME variable
      ansible.builtin.debug:
        msg: "{{OUT_UPTIME.stdout}}"

    - name: declaring the variable
      ansible.builtin.set_fact: 
        STATUS_CODE_VAR1: "{{OUT_UPTIME.rc}}"
  
    - name: Printing exit code 
      ansible.builtin.debug:
        msg: "{{STATUS_CODE_VAR1}}"

