- name: Demo on using variables
  hosts: all
  vars:
     URL: play.google.com
  vars_files:
    - demo.vars.yaml
  tasks:
    - name: Printing URL
      ansible.builtin.debug:
        msg: "{{URL}}"

    - name: Printing URL
      ansible.builtin.debug:
        msg: Value of URL is {{URL}}
      vars:
        URL: task.google.com

    - name: Printing CLI_URL
      ansible.builtin.debug:
        msg: Value of CLI_URL is {{CLI_URL}}
      
