- name: copying mysql repo
  ansible.builtin.copy:
    src: "{{COMPONENT}}.repo"
    dest: /etc/yum.repos.d/{{COMPONENT}}.repo

- name: Install mysql
  ansible.builtin.yum:
    name: 
    - mysql-community-server
    - MySQL-python
    state: installed

- name: starting mysql service
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: true

- name: Checking Default Root Password
  block:
    - name: Fetch MySQL version to check the DB Connection
      mysql_info:
        login_user: root
        login_password: "{{DB_PASSWORD}}"
        filter: version
  rescue:
    - name: Load MYSQL Log File
      ansible.builtin.slurp:
        src: /var/log/mysqld.log
      register: mysql_log

    - name: Declare Facts
      ansible.builtin.set_fact:
        DEFAULT_PASS: "{{mysql_log['content'] | b64decode | regex_findall('.*temporary password.*') | join(' ') |split(' ') | last }}"

    - name: Change MySQL
      ansible.builtin.shell: echo "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{DB_PASSWORD}}';" | mysql --connect-expired-password -uroot -p"{{DEFAULT_PASS}}"

- name: Check Validate plugin exists
  ansible.builtin.shell: echo "uninstall plugin validate_password;" | mysql -uroot -p{{DB_PASSWORD}}
  ignore_errors: yes

- name: Download and extracting MySQL 
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: Load Schema
  community.mysql.mysql_db:
    state: import
    name: all
    target: /tmp/mysql-main/shipping.sql
    login_user: root
    login_password: "{{DB_PASSWORD}}"
