- name: configuring Erlang
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | sudo bash

- name: configuring YUM repositories
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash

- name: Install rabbitmq
  ansible.builtin.yum:
    name: 
    - rabbitmq-server
  state: installed

- name: starting rabbitmq
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: restarted
    enabled: true

- name: adding appuser to rabbitmq 
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present

- name: set hostname
  ansible.builtin.shell: set-hostname {{COMPONENT}}