- name: configuring nodejs repo
  ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash -

- name: Install nodejs
  ansible.builtin.package:
    name: nodejs
    state: present

- name: creating the application user account
  ansible.builtin.user:
    name: "{{APPUSER}}"
    comment: roboshop service account

- name: downloading and extracting the component
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/{{COMPONENT}}/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: cleanup of old content
  ansible.builtin.file:
    path: /home/{{APPUSER}}/{{COMPONENT}}/
    state: absent

- name: Copy files to the roboshop home directory
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/{{APPUSER}}/{{COMPONENT}}/
    remote_src: yes
    owner: "{{APPUSER}}"
    group:  "{{APPUSER}}"

- name: Install node ja package
  community.general.npm:
    path: /home/{{APPUSER}}/{{COMPONENT}}/

- name: Copying systemd service file
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: restarting service
  ansible.builtin.systemd:
    state: started
    name: "{{COMPONENT}}"
    daemon_reload: yes

- name: set hostname
  ansible.builtin.shell: set-hostname {{COMPONENT}}