- name: configuring nodejs repo
  ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash -

- name: Install nodejs
  ansible.builtin.package:
    name: nodejs
    state: present

- name: creating the application user account
  ansible.builtin.include_role:
    name: common
    tasks_from: create-user

- name: downloading and extracting the component
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: Install node js package
  community.general.npm:
    path: /home/{{APPUSER}}/{{COMPONENT}}/

- name: configuring service
  ansible.builtin.include_role:
    name: common
    tasks_from: configure-service

- name: set hostname
  ansible.builtin.shell: set-hostname {{COMPONENT}}